<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Password_btnShowPassword</name>
   <tag></tag>
   <elementGuidId>9420ad57-5502-4c48-8a2c-a38af211b94f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnShowPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='btnShowPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>122f24dc-76a7-4ee9-b196-b35e8845d9a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/resources/projectx/images/login/eye.svg</value>
      <webElementGuid>a5a04c34-e0c0-42bc-8488-7a1efc41941e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>eye</value>
      <webElementGuid>06fd7dc1-23d0-49e6-bd45-46909abb49c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnShowPassword</value>
      <webElementGuid>252e61d1-50dc-4172-9b34-55903da16288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnShowPassword&quot;)</value>
      <webElementGuid>7cf484f5-1625-4fd8-8db1-ce775d3fdd63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='btnShowPassword']</value>
      <webElementGuid>d9cbe049-da52-4006-a9ce-a1c032b39233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerFunderForm']/div[4]/div/div/button/img</value>
      <webElementGuid>0c88b466-5e89-4f42-83d1-cb20922a2ebc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='eye']</value>
      <webElementGuid>3c730f01-6f64-454f-a451-d64a70370443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
      <webElementGuid>6369e605-2e4d-43e7-a716-9e0b7b4d8553</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/resources/projectx/images/login/eye.svg' and @alt = 'eye' and @id = 'btnShowPassword']</value>
      <webElementGuid>82b5fbb3-33a1-4603-b936-9e7e043dd247</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
