<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Lengkap_name</name>
   <tag></tag>
   <elementGuidId>c29bf35f-ad08-45d2-918e-12c5b9351c7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#registerNamaFunder</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='registerNamaFunder']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>81fecf42-382a-4c4b-9db6-cdca27279666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>010a7515-2cd9-49d2-ae4e-3a13ce5c1a78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>88d2d7c0-e102-4c1c-acf5-136d288ca689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registerNamaFunder</value>
      <webElementGuid>d218a6f9-6274-44b6-8d60-f42aa6ab7fc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>2c475fb8-5b98-4107-bc51-33dca3ce431b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama Lengkap Sesuai e-KTP</value>
      <webElementGuid>2e633ef1-6e12-4cf8-bd1c-bd9e6690ebb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerNamaFunder&quot;)</value>
      <webElementGuid>07a1d3e0-0f75-4d60-a1aa-31c136ba2519</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='registerNamaFunder']</value>
      <webElementGuid>7df2bf9c-583f-45c2-89d0-2fb4e35f1773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerFunderForm']/div/input</value>
      <webElementGuid>20845f13-5f74-46b9-b4a7-27329db3a675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>4a4673a6-90cc-4bdb-9153-59041a607a64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'registerNamaFunder' and @name = 'name' and @placeholder = 'Nama Lengkap Sesuai e-KTP']</value>
      <webElementGuid>eae4bbad-f5a6-4a5e-9424-0f9e475434ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
