<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No. Handphone_phone</name>
   <tag></tag>
   <elementGuidId>57ecd3d6-2c6f-481d-83cd-44e7e1499dbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LenderPhone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='LenderPhone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b2f3c70a-8f29-4283-a42f-1dd91448da15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ea80b4d6-6c8e-48bf-8e11-66932c085552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>891f23e0-fa76-4477-956c-a8be21c98449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LenderPhone</value>
      <webElementGuid>827d87d1-7084-4ebb-a6cc-590bdd1f565c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>f98935a5-4016-4632-bf3c-d050136841d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nomor Handphone</value>
      <webElementGuid>1ccc8717-6310-40f3-9c44-19b35f6fb62e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4c90fb20-d6a6-47c4-a438-31bb5cd2ff15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LenderPhone&quot;)</value>
      <webElementGuid>0128cda5-a861-497a-aabb-be6b751be11b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LenderPhone']</value>
      <webElementGuid>45c67a66-9e52-4ca3-a4ec-74bdc1d06138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerFunderForm']/div[3]/input</value>
      <webElementGuid>b2ee9ac9-6033-4dfd-aa34-cebc1025309f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>2254097d-3b58-438d-a252-7f9fa64568f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'LenderPhone' and @name = 'phone' and @placeholder = 'Nomor Handphone']</value>
      <webElementGuid>ab3b470a-7b8f-43d4-976e-a1463dfd85ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
