<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kode Referral (Opsional)_relamiCodeReferral</name>
   <tag></tag>
   <elementGuidId>d3a2e806-6c63-4927-b642-605a28da4bb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#kodeRef</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='kodeRef']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>40e51775-9304-48ea-ab58-aba206a5731c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a3527801-7e7c-4653-a516-44486ff7bc1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f07626ea-a504-4ea0-a7db-3bc6161a547c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kodeRef</value>
      <webElementGuid>a6d7d151-842b-480e-8912-ca308737039d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>relamiCodeReferral</value>
      <webElementGuid>cb459aca-c6b4-4c97-8b47-ca2536361b4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Kode</value>
      <webElementGuid>0b424ff8-ad6f-416b-9d4f-30af91438eb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>c75f0147-157a-47e7-8ec9-cb24f9822d13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kodeRef&quot;)</value>
      <webElementGuid>51ed5513-6b7e-4b24-b050-10e9d8144cb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='kodeRef']</value>
      <webElementGuid>e8986af0-2485-4c36-b391-b52465c86720</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerFunderForm']/div[6]/input</value>
      <webElementGuid>34fd4285-2a18-4f9e-a1a1-3772c6c897c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>2b38a149-8ade-4047-a460-594345a28d75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'kodeRef' and @name = 'relamiCodeReferral' and @placeholder = 'Kode']</value>
      <webElementGuid>f8bbc057-df96-44af-ae69-f8b1ddd17b53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
