<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Kirim Ulang Aktivasi Email (1)</name>
   <tag></tag>
   <elementGuidId>f12258e4-fd41-445a-8ba5-a2b82e9fa203</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sendEmailActivation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='sendEmailActivation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7f03cc20-e1b2-44bb-9053-3e091c3ec7f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:</value>
      <webElementGuid>d22d0d3e-7bf7-433f-88e4-1f04486f89c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sendEmailActivation</value>
      <webElementGuid>f65a0954-7ce0-4f6a-9f40-5c7143ef2118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-full-secondary</value>
      <webElementGuid>41bf5b20-11af-479d-8a40-ae04189b1e59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kirim Ulang Aktivasi Email</value>
      <webElementGuid>82bd0221-4cb7-4b6c-9603-f4589f6b02b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sendEmailActivation&quot;)</value>
      <webElementGuid>fdb8b734-dcc8-4cb1-850c-79b95451daeb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='sendEmailActivation']</value>
      <webElementGuid>c508f1df-7c5e-4cdb-826a-162cfbd4c71d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Kirim Ulang Aktivasi Email')]</value>
      <webElementGuid>610a1a6a-d526-47e5-9d27-cb57834c5aa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terima Kasih!'])[1]/following::a[1]</value>
      <webElementGuid>9f57979c-c39f-47a2-8991-9a6904442e98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registrasi Pemberi Dana'])[1]/following::a[1]</value>
      <webElementGuid>375e99e2-5cb3-4671-ae4c-5327e7a98bca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='masuk'])[1]/preceding::a[1]</value>
      <webElementGuid>edb2c9df-7b2f-43ad-8bf1-4e7c0d2b2340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::a[2]</value>
      <webElementGuid>0edfd63c-2905-4c30-ac74-c13ca9c543cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kirim Ulang Aktivasi Email']/parent::*</value>
      <webElementGuid>307ce92d-0808-4aa7-afa0-c2e456d9f055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:')]</value>
      <webElementGuid>8f689c0b-d0fb-461d-86ad-341bb677c1f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/a</value>
      <webElementGuid>75e79a13-da0b-417b-876d-35b219aa4baa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:' and @id = 'sendEmailActivation' and (text() = 'Kirim Ulang Aktivasi Email' or . = 'Kirim Ulang Aktivasi Email')]</value>
      <webElementGuid>6af5c654-eb53-47ee-993c-066595018acd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
