<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bagaimana Kamu tahu ALAMI</name>
   <tag></tag>
   <elementGuidId>cbd6f00d-116b-4257-b7e5-3f6a2c9c0cb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='registerReferralOther']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;registerReferralOther&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>da339d8d-0a48-4d88-ad9a-86dab1d04088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8e4b6e2b-426a-46da-97d4-1181a1cccafd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>registerReferralOther</value>
      <webElementGuid>f1cb2b28-dac4-47cc-9594-e3cf6418a70e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-register</value>
      <webElementGuid>0e50f2f7-6464-4330-903e-53bc3e02d402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Lainnya</value>
      <webElementGuid>f20bc9d1-5c2a-4a61-949f-7c1e8191ff2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerFunderForm&quot;)/div[@class=&quot;form-group CoregisterReferralOther&quot;]/input[@class=&quot;form-control input-register&quot;]</value>
      <webElementGuid>e089d256-cb3c-4b8b-97f3-da3d93bb177e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='registerReferralOther']</value>
      <webElementGuid>d3ff5699-aadc-4a7d-a8aa-98948370b928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerFunderForm']/div[8]/input</value>
      <webElementGuid>d4897d7f-6d41-4544-bebc-e96fb771ac70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/input</value>
      <webElementGuid>2b5c743e-10ca-47da-be4e-947478569a1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'registerReferralOther' and @placeholder = 'Lainnya']</value>
      <webElementGuid>60a89c94-ac4f-4388-8177-4742939c3cf5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
