<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Saya tertarik update info terbaru ALAMI</name>
   <tag></tag>
   <elementGuidId>8af53210-e36c-46a7-b918-cb8efd7861f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;langganan&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='langganan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c7a3bd38-8d6c-4c4e-99db-bf44bd0fae99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>30746e5c-8bc6-4530-aa3c-56bcda08454f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>langganan</value>
      <webElementGuid>7e6a06a7-6bbf-4806-b778-6c390848d0f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerFunderForm&quot;)/div[@class=&quot;wrapper-footer&quot;]/label[@class=&quot;text-light-check&quot;]/input[1]</value>
      <webElementGuid>a5b168f1-c88e-4058-a3bc-6027dc79d7b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='langganan']</value>
      <webElementGuid>1d1cd89f-a670-40c3-b3b7-ebb3b4b8a8ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerFunderForm']/div[2]/label/input</value>
      <webElementGuid>944d5607-8fe8-4c79-ae11-de29a18e21c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>4dc73219-b1af-4373-bd7b-1468bc962271</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'langganan']</value>
      <webElementGuid>af821825-b302-4d0a-a3b9-8ce422272da1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
