<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Saya sudah membaca dan setuju dengan</name>
   <tag></tag>
   <elementGuidId>5790f10c-dd94-40de-8359-00bdecc8df96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='setujuKebijakan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#setujuKebijakan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ad1e6ec1-77c2-49b8-87e4-0be57aa722bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a9d48199-0c2c-44af-bfb5-60518006e980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>setujuKebijakan</value>
      <webElementGuid>437263e6-40ea-4d21-bc88-21baa281f178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>setujuKebijakan</value>
      <webElementGuid>857f0392-86f8-45c0-bcf2-45e72b1d4845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;setujuKebijakan&quot;)</value>
      <webElementGuid>dde21252-c0a1-41a8-abaf-7d8ca1a0ae69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='setujuKebijakan']</value>
      <webElementGuid>c915b032-21ec-47a4-ae88-d30a5f08e46d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='checkboxKebijakan']/input</value>
      <webElementGuid>f38ae3dd-2284-426d-b285-6c41dd94abb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/input</value>
      <webElementGuid>2b4d9f52-a5a9-4bb7-bb40-ac82e00958ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'setujuKebijakan' and @id = 'setujuKebijakan']</value>
      <webElementGuid>413af62f-70f0-43e4-9334-4ebd8011fc84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
