<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Tuliskan nama dengan benar</name>
   <tag></tag>
   <elementGuidId>5a8317f2-e872-4923-bf0f-e55e4696cf42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#registerNamaFunder-error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='registerNamaFunder-error']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>dea937fc-4169-4de2-992c-ad022c3d1059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registerNamaFunder-error</value>
      <webElementGuid>b2e66811-dfb4-4067-8d6c-87c075becc51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>fd822823-e172-4f3d-8b40-ede7171eafbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>registerNamaFunder</value>
      <webElementGuid>f1b595f4-49b0-42f8-a0a9-5907d90bd694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tuliskan nama dengan benar</value>
      <webElementGuid>e81a1457-ca19-4b59-aa2a-3b5dbd712eba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerNamaFunder-error&quot;)</value>
      <webElementGuid>8fd1c2a1-cc19-4362-8055-2dcf156a3145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>7fb9ecd7-0a7a-4eef-bcb7-5999cd0a0b3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registerNamaFunder-error</value>
      <webElementGuid>19261425-3a76-466e-94ff-c920c52c9f3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>7a7d9275-a54f-4d0c-8098-5770acc7e24d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>registerNamaFunder</value>
      <webElementGuid>f9f5959d-8f02-4cb0-ba0b-c39472f9e280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tuliskan nama dengan benar</value>
      <webElementGuid>2883e7e9-eded-4548-9894-856909847d9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerNamaFunder-error&quot;)</value>
      <webElementGuid>9b1a4d85-cd25-4f60-8151-e7b2ffb67f5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='registerNamaFunder-error']</value>
      <webElementGuid>17c4e48b-1a46-481c-9614-cbcb93ba1db5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerFunderForm']/div/label[2]</value>
      <webElementGuid>4d2d0b0f-bbf2-49ae-8e72-2909a9431053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Lengkap'])[1]/following::label[1]</value>
      <webElementGuid>1f51e819-af89-46ed-983e-12b662dadef3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Syariah penuh. Impact nyata.'])[1]/following::label[2]</value>
      <webElementGuid>b2c53131-b29f-4500-b5c1-577459f17d0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/preceding::label[1]</value>
      <webElementGuid>d7429327-66d7-4b25-b3e4-dde53f86b012</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bagian ini harus diisi'])[1]/preceding::label[2]</value>
      <webElementGuid>63a2bae8-d85a-4c0f-8695-5d6528911769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tuliskan nama dengan benar']/parent::*</value>
      <webElementGuid>09b3ae1d-481b-405c-818c-9d513fd1cb4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]</value>
      <webElementGuid>611c16fd-9e9f-445c-9c62-f0e6226e36c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'registerNamaFunder-error' and (text() = 'Tuliskan nama dengan benar' or . = 'Tuliskan nama dengan benar')]</value>
      <webElementGuid>7c337aa0-a2cf-41cb-9f34-fe3334927720</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
