<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Email Sudah digunakan</name>
   <tag></tag>
   <elementGuidId>6fcaac71-0c8f-4f45-a0af-edcf3c8add61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#registerEmailFunder-error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='registerEmailFunder-error']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>7fae122a-7c03-435d-8737-c1241216662c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registerEmailFunder-error</value>
      <webElementGuid>e191c336-0427-459b-b2f2-e039e9467e1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>66171bd7-fac3-49e7-804a-041cf8156a69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>registerEmailFunder</value>
      <webElementGuid>9dad1aac-df07-4d5a-93f1-4f30d764a97e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email Sudah digunakan</value>
      <webElementGuid>b1aefb60-0758-42cf-a117-ccc0a66b65d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerEmailFunder-error&quot;)</value>
      <webElementGuid>b98095a2-6999-44cc-9ce3-6e126b2e9af9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='registerEmailFunder-error']</value>
      <webElementGuid>6de219a5-9dd7-4828-b9a8-7872e85eeeb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerFunderForm']/div[2]/label[2]</value>
      <webElementGuid>4b8f5469-6b78-4d4a-bc93-f127aab9354c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::label[1]</value>
      <webElementGuid>c99dceb9-9432-47ef-85e9-890e0122f17d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Lengkap'])[1]/following::label[3]</value>
      <webElementGuid>3e9742d4-d894-43a0-a8bd-b4632ddee67e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Note:'])[1]/preceding::label[1]</value>
      <webElementGuid>3d36cbc4-0b35-4738-bfef-b3b44fbac6c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Email Sudah digunakan']/parent::*</value>
      <webElementGuid>f481fe63-cc1b-4e4c-8608-f4b8ebe2f326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label[2]</value>
      <webElementGuid>5bee487e-4d7c-4261-919c-cb5c8ab86c28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'registerEmailFunder-error' and (text() = 'Email Sudah digunakan' or . = 'Email Sudah digunakan')]</value>
      <webElementGuid>a193c91f-67a8-401b-8cf6-3c172025bdc1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
