<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Bagian ini harus diisi</name>
   <tag></tag>
   <elementGuidId>0a8ea493-0a00-404a-b05a-7aee04162b8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LenderPhone-error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='LenderPhone-error']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>db555eeb-8ab0-40f5-8446-5fd8ad5d8e46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LenderPhone-error</value>
      <webElementGuid>32e45d31-4a5c-47bb-abb6-80c6efc7b0a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>62fe5f07-f110-430f-8b1a-30e9ca300f53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>LenderPhone</value>
      <webElementGuid>ed66fd7e-2d62-4b1c-a235-d5f45a4d2e69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bagian ini harus diisi</value>
      <webElementGuid>0efd223f-d442-4809-998d-63f439329e16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LenderPhone-error&quot;)</value>
      <webElementGuid>e60f3055-ba80-4f52-8444-0f45f6308b8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>6ecf36dd-8b71-4f8c-bbec-c3940c7b8580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LenderPhone-error</value>
      <webElementGuid>390f25ce-0abb-428a-ba1b-b7bd179dd53c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>b3142dbc-a2e1-429c-8628-5ea61430f563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>LenderPhone</value>
      <webElementGuid>2b278aba-db7e-4fe9-be10-02acef34c8e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bagian ini harus diisi</value>
      <webElementGuid>d0fc5672-1e2f-47ed-bc88-98a64ac106cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LenderPhone-error&quot;)</value>
      <webElementGuid>c5ea1be7-cb49-4f43-b293-d90f6b5fcb7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='LenderPhone-error']</value>
      <webElementGuid>a6608285-2b3d-4fa4-a1f8-43de6d3a8e02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerFunderForm']/div[3]/label[2]</value>
      <webElementGuid>a20167a8-2134-49a5-8343-5f922a2b9f9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No. Handphone'])[1]/following::label[1]</value>
      <webElementGuid>1799ba82-921f-4708-b3cb-d351afb8c507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Note:'])[1]/following::label[2]</value>
      <webElementGuid>d059c6ff-8ec6-4ec4-b9a1-ac6d60d9946d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/preceding::label[1]</value>
      <webElementGuid>fd61b0be-b51b-4dc5-814b-997a7c94d769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bagian ini harus diisi'])[2]/preceding::label[2]</value>
      <webElementGuid>1ca7879e-2e63-4870-9fec-a48bdae66ac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bagian ini harus diisi']/parent::*</value>
      <webElementGuid>0ab5fa40-719d-402b-afd8-efb0713272d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/label[2]</value>
      <webElementGuid>85d1b816-c135-4b85-af28-3f3db6637e09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'LenderPhone-error' and (text() = 'Bagian ini harus diisi' or . = 'Bagian ini harus diisi')]</value>
      <webElementGuid>623f30a8-56f9-4fe3-8d02-f96f14d3ac6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
