<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_silakan isi email dengan format yang benar</name>
   <tag></tag>
   <elementGuidId>e02c4842-e558-45ab-8ba6-ab143f990fb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#registerEmailFunder-error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='registerEmailFunder-error']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>279c8878-22cd-48e0-a7ca-0ca5095fef3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registerEmailFunder-error</value>
      <webElementGuid>1a3bc006-dd11-4ad9-9e1d-22aa7d2027e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>56aa6dee-1ce8-4313-9760-267a14ebdc6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>registerEmailFunder</value>
      <webElementGuid>d0b6ed91-baba-4a2b-8b53-d981bc6cf560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>silakan isi email dengan format yang benar</value>
      <webElementGuid>7de58862-8a03-480f-a2b2-3e9147960183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerEmailFunder-error&quot;)</value>
      <webElementGuid>49555e67-1161-4e64-bc34-42baf3d4fcb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>6f49b884-4a12-4669-bcba-22992c2d2d54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registerEmailFunder-error</value>
      <webElementGuid>7bba9bbb-994c-4dd5-9aaa-ae4e542b7370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>2c970f50-4db2-4e08-a054-4a67c451c725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>registerEmailFunder</value>
      <webElementGuid>e2231edc-05b3-4f9a-89ad-f36a351ba76a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>silakan isi email dengan format yang benar</value>
      <webElementGuid>a1956b6e-0dfb-4c44-a0da-cf17d3654bb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerEmailFunder-error&quot;)</value>
      <webElementGuid>0b239de3-487a-473d-8cda-24f804e1b997</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='registerEmailFunder-error']</value>
      <webElementGuid>c2515e65-ce8c-49cd-9123-e24eebfc93ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerFunderForm']/div[2]/label[2]</value>
      <webElementGuid>8bdefcf4-4a7e-4bae-8d1d-32000568ea54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::label[1]</value>
      <webElementGuid>02a41bf0-deb8-4a90-b8a3-4314407eb93b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tuliskan nama dengan benar'])[1]/following::label[2]</value>
      <webElementGuid>fa16624a-61a1-438d-901a-8ff5238218a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='silakan isi']/parent::*</value>
      <webElementGuid>bdc53dc1-fa74-4a55-aa99-bb99330ed10f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label[2]</value>
      <webElementGuid>d3a9aee0-15ea-4f7e-ae34-f5db1a194c09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'registerEmailFunder-error' and (text() = 'silakan isi email dengan format yang benar' or . = 'silakan isi email dengan format yang benar')]</value>
      <webElementGuid>661daf4e-ff49-49ae-816b-8df7af129f59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
