<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>registerReferal</name>
   <tag></tag>
   <elementGuidId>0b52c30f-1678-4997-a400-2751350c9152</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#registerReferralId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='registerReferralId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8c6030da-d915-4e9d-a86e-e914943fa961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registerReferralId</value>
      <webElementGuid>638eb283-212d-443a-bdd9-a5a52370152f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>registerReferralId</value>
      <webElementGuid>f8f460a8-906f-4e10-9301-946902d046dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>61247aea-fd8b-4532-97ae-63bccd29e5a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    -- Silahkan Pilih --
                                    Facebook
                                    Instagram
                                    LinkedIn
                                    Lainnya
                                </value>
      <webElementGuid>5b1a172c-a14e-4df1-95fa-e2e8b015a1dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerReferralId&quot;)</value>
      <webElementGuid>31c1b9e1-112d-4f59-baef-d9155adec631</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='registerReferralId']</value>
      <webElementGuid>7bfc243f-661c-41b7-bcae-18312be5e5b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerFunderForm']/div[7]/select</value>
      <webElementGuid>bbb45848-8146-4924-afe4-673784ed0763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bagaimana Kamu tahu ALAMI? (Opsional)'])[1]/following::select[1]</value>
      <webElementGuid>ce8c1a39-30db-4359-af9f-0fca02b53be8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kode Referral (Opsional)'])[1]/following::select[1]</value>
      <webElementGuid>369f9394-2733-437d-8a94-cc9b7cbe5ff9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lanjutkan'])[1]/preceding::select[1]</value>
      <webElementGuid>94c698b8-550f-4c27-b95d-d41b4c243f33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar disini'])[1]/preceding::select[1]</value>
      <webElementGuid>bafc3a51-56cd-42c1-920e-25e0627da3e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>d881fe5c-6dad-4592-ac37-37d688c500e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'registerReferralId' and @name = 'registerReferralId' and (text() = '
                                    -- Silahkan Pilih --
                                    Facebook
                                    Instagram
                                    LinkedIn
                                    Lainnya
                                ' or . = '
                                    -- Silahkan Pilih --
                                    Facebook
                                    Instagram
                                    LinkedIn
                                    Lainnya
                                ')]</value>
      <webElementGuid>a9dc6be9-fb18-45b6-8e81-5f4cce059704</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
