<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Assalamualaikum</name>
   <tag></tag>
   <elementGuidId>fb6b53bc-1190-46b6-b0e7-03f1f269a097</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.heading-5-homepage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='#HijrahFinansial. Membangun Keuangan Syariah di Indonesia'])[1]/following::div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>456b4d48-18ab-4ba3-8404-93b6ed73e094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>heading-5-homepage</value>
      <webElementGuid>5f673711-280a-4219-8c0b-39de0884568a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Assalamualaikum</value>
      <webElementGuid>b815c00e-1b88-4496-9a68-b2911bad55b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;page login&quot;]/main[@class=&quot;full&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-6 px-0&quot;]/div[@class=&quot;right-side&quot;]/div[@class=&quot;header-login&quot;]/div[@class=&quot;heading-5-homepage&quot;]</value>
      <webElementGuid>3927c5ae-1d90-4616-b177-dd13a16769a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#HijrahFinansial. Membangun Keuangan Syariah di Indonesia'])[1]/following::div[4]</value>
      <webElementGuid>947feb88-b209-4e3f-b350-8448356a95e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lupa Kata Sandi'])[1]/preceding::div[4]</value>
      <webElementGuid>ce54b239-5656-4ceb-ad07-26c904cc13ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk Ke Akun Saya'])[1]/preceding::div[4]</value>
      <webElementGuid>4b48fb27-4fcf-46dc-97a1-4424c41bc64c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Assalamualaikum']/parent::*</value>
      <webElementGuid>bde764e8-87f3-4b75-a5c2-4bb48eb2419f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div</value>
      <webElementGuid>f18c0828-0cc6-4386-8ef9-c7ee658c684f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Assalamualaikum' or . = 'Assalamualaikum')]</value>
      <webElementGuid>4f08ef70-8870-4aa8-8ca7-8e54c5827695</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
