<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Assalamualaikum_btnShowPassword</name>
   <tag></tag>
   <elementGuidId>b9d97339-652c-47b9-8512-a968f7cc4313</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnShowPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='btnShowPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>17a0a8bb-5598-4e89-960b-e5ae0196b985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/resources/projectx/images/login/eye.svg</value>
      <webElementGuid>0e0277b7-cd13-49b7-ada6-9d6646389abe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>eye</value>
      <webElementGuid>dc8fb42a-659e-47bf-9c60-42a6635b7ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnShowPassword</value>
      <webElementGuid>13b17b7e-c596-4be4-8714-dd9f3da3d8d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnShowPassword&quot;)</value>
      <webElementGuid>9e3692c6-3504-4edf-8a56-4f994deef23f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='btnShowPassword']</value>
      <webElementGuid>4f6a9e8b-79b6-4bed-b876-16364cefb576</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='eye']</value>
      <webElementGuid>46bc8fe1-51af-4685-be37-710a8f7151e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
      <webElementGuid>2c4496cf-3f68-4b8c-a015-6e81c4397666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/resources/projectx/images/login/eye.svg' and @alt = 'eye' and @id = 'btnShowPassword']</value>
      <webElementGuid>f7c89969-3efe-4a0e-8a30-59dad9202d2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
